# commit to be tagged for the new release
commit = "HEAD"

project_name = "pulumi-provider-talos"
github_repo = "siderolabs/pulumi-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.0-alpha.10"
pre_release = true

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
Talos TF provider: v0.1.0-alpha.10
"""
