# commit to be tagged for the new release
commit = "HEAD"

project_name = "pulumi-provider-talos"
github_repo = "siderolabs/pulumi-provider-talos"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.0-alpha.7"
pre_release = true

[notes]
