name: Upgrade bridge

on:
  workflow_dispatch:
  schedule:
    # At 05:00 on Monday
    - cron: 0 5 * * 1

jobs:
  upgrade_bridge:
    name: upgrade-bridge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@v0.0.12
        with:
          kind: bridge
          email: ringo@de-smet.name
          username: "Ringo De Smet"
        env:
          GH_TOKEN: ${{ secrets.UPGRADE_PROVIDER_TOKEN }}
